language: go

go:
  - 1.13.x

script:
  - bash ./build/build.sh

deploy:
  provider: releases
  api_key:
    secure: "N/lUwrfa8mrJ7bkURWn9Ku+zCe6oe7x8umJPGqLgpuzWlWYnbYok890iF1SZhjeu0CMeV0TS92vRGPcg9oPERFwWiRd/wIONdgDFDOXthAF2KkgfDe4l0X7XNldWn/yAua0z3a5iM8TICQTwuJzOY26rAL3TqIZJpF7DBAtUVKqR6rKR4UrXe9EFqFYiDcaqPZWVc0kauwWY8hpCQo/M94PgFaAv7xyW0zsXorUIlCD05o/S3LDh274mq1ZW/Q4SzabH+RpR0Bz/kAmUgeu+YbIu9yvFOEOpalepL6ML5qIhNwzWhBGhmLP8kdGhnWRKNuLlOKA7BYSUQ+2l0i1WdFaVDsK/73FPNm3cAM6ItNd5cjeA7jbA3b4JZE641JlOQO+alWrejxUjjl9gA8phsMLtwXnHM3J/o76D/xFk/AG/VxB5VDm12ryqXCTq8ZkGyXjGvgzWITBqiY2MyX8XKB0yNMWxoCQQ6t/Mrjxiu1A0OWTVBHL54ts5hIXjGCAhXbZSOZ0Y4c3M6ldeZOwewReCrlJgDRseExE0nC3Mb7eq9Gx/Be82IROOzvrnETDlBN9i680gJGDlnalMWlrlkszatjuEoMVzczigKic6Ry/4ZVOHMaOSfzwr9Z+P4BthFZcl19va5TJRZN9Jc6yXuCqNqJNQCfgOeSbF/JE+QNM="
  file_glob: true
  file: "distributions/*"
  skip_cleanup: true
  on:
    tags: true