language: go
go:
- 1.13.x
script:
- bash ./build/build.sh
deploy:
  provider: releases
  api_key:
    secure: uYBQu3f7ALH56H1RIrl3bfHEFoEL72AE0Yzt311ya5GtpJ3szWI+YoZS7A0kxMXmllSl07wajRVwGljPFezUPK5GYoslhhnXyu76BljfP7OluU48JzHg19eZpKw1eGXZPkfF8FPormJlvwP6Y4pl45PsUGv/eUtT/zkqLFJfC1Sb1/wslcOtgf2C/Jho1VVInMx9KW2ZRC5jdJmhUTk6snBffZojUOCRIeCz8f0Y2jacQlBXh+gK90YcaxBPtxi9sGyNHg2t2/m5Gl9gc0DIs9Kh0sT6oAW4vF0gx7Rox2g8HUGk8air9enWp3bLyuV06O8RKNV3lCJSYc/6Ahv55XSZ6kYotH1auIm8zqFEQerqapq30fQ7vM2t/rjkXdqRq0QPxvIDB7wWnD8X8Qr74yym3gChBn9IqMwc+hht0/IjkJdEc+Nw/MLaZqUD9Attac6j9yijiX5XsfvkHlINqzlrEAX49iplXsZjDnX5FRPCYP1qZfo0dHZx774ixhXuCTym2perY7EHEi9n8mjFgEuDQX6g4y23C1N1jBgBwNJZfMh2+zaVp0sIoALxuyykHNXPTuUZK5QdpMKIAT3yVDj9tVnDR+5yzV+jT0C0HNaPmahzRyXUcXLuGyvv9ivv0Dhsw9qXH318KxTNzhukKxDgQXxFfpqRgKgFB0xpJbg=
  file_glob: true
  file: distributions/*
  on:
    repo: zendern/getprs
    tags: true